version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: azrim-umbrel-shoko_server_1
      APP_PORT: 8111

  server:
    image: ghcr.io/shokoanime/server:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - ${APP_DATA_DIR}/data/config:/home/shoko/.shoko
      - ${UMBREL_ROOT}/data/storage/downloads/anime:/mnt/anime
